### ISSUE TITLE
ASP.NET Core 3.1 Instructions

### ISSUE THREAD

**Issue by Legends** [johnnyreilly/jquery-validation-globalize#13]
As I am using `jquery.validate.unobtrusive` I actually do not have to configure anything else to make validation work with `jquery-validation-globalize`, right?

I've added the following scripts:

  ```
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

    <!-- cldr scripts (needed for globalize) -->
    <script src="~/lib/globalize/cldr.js"></script>
    <script src="~/lib/globalize/event.js"></script>
    <script src="~/lib/globalize/supplemental.js"></script>

    <!-- globalize scripts -->
    <script src="~/lib/globalize/globalize.js"></script>
    <script src="~/lib/globalize/number.js"></script>
    <script src="~/lib/globalize/date.js"></script>

    <script src="~/lib/globalize/jquery.validate.globalize.js"></script>
```

I am also using `jquery.validate.unobtrusive`.

**When I hit the submit button now after adding all the scripts after the `jquery.validate.unobtrusive` script, the form gets submitted to the server without validation to take place!**

Do I have to make some special api calls to initialize the whole thing correctly?
If I remove `jquery.validate.globalize.js` from teh scripts above the form gets validated again.

Then I thought perhaps I should call `Globalize.locale("de-DE")` but then I get:

> globalize.js:194 Uncaught Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/likelySubtags`

Isn't `supplemental/likelySubtags` part of `cldr.js`?

Thanks in advance!

**Comment by johnnyreilly** [comment]
Sorry this library isn't supported any more.

**Comment by Legends** [comment]
Ah ok, what's used now for globalized validation if you don't mind asking?
Thanks!

**Comment by johnnyreilly** [comment]
Don't mind you asking at all! I'm not in that tech space at the moment and so I don't know I'm afraid. I'm not a jQuery user anymore. (Never thought I'd say that!)

**Comment by Legends** [comment]
haha, yes that's true, I was just wondering, I would have to download all the scripts including `jquery` just for form validation.

I guess I have to rethink my approach for forms validation.

ASP.NET Core v3.x [docs ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0) mention `jQuery Validation` that's why I went this way, but I guess it's obsolete as explained above.

Thanks again!
