### ISSUE TITLE
TypeError: n.validator is undefined

### ISSUE THREAD

**Issue by AndersBillLinden** [johnnyreilly/jquery-validation-globalize#5]
Using jquery-validation-globalize.min.js, cant see a version number, I get an error when the script loads at column 22: TypeError: n.validator is undefined

I am Using firefox with firebug, the error is on the the first occurence of the word min:
(function(n,t){var i={min:n.validator.methods.min,max:n.validator.methods.max,ra...

**Comment by johnnyreilly** [comment]
Closed due to lack of information
