### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by emersonsoares** [johnnyreilly/jquery-validation-globalize#6]
I'm upgrading the management of frontend packages to [Bower](http://bower.io), and saw that this extension does not exist in bower directory.

**Comment by RodrigoGroener** [comment]
A Bower package would be nice. +1

**Comment by Deilan** [comment]
+1

**Comment by johnnyreilly** [comment]
Good idea - will try to do this at some point.

**Comment by johnnyreilly** [comment]
Done - you can `bower install jquery-validation-globalize --save` to your heart's content :heart:

**Comment by emersonsoares** [comment]
:clap:
