### ISSUE TITLE
Support for Globalize 1.x

### ISSUE THREAD

**Issue by samcic** [johnnyreilly/jquery-validation-globalize#8]
The Globalize project is now on version 1.x. A few breaking changes have been made, as explained here: https://github.com/jquery/globalize/blob/master/doc/migrating-from-0.x.md (for example, parseFloat has been replaced with parseNumber).

Are there any plans to update this project to support the new Globalize API?

**Comment by johnnyreilly** [comment]
Hi @samcic,

This has long been on the backburner for me.  Having just been reminded by [this comment](https://github.com/jzaefferer/jquery-validation/issues/581#issuecomment-116329471) from @jzaefferer I'll try to take a look.

**Comment by sebrojas14** [comment]
Please!

**Comment by johnnyreilly** [comment]
It's still on the list I promise!

**Comment by johnnyreilly** [comment]
Okay - first cut nearly ready...

**Comment by johnnyreilly** [comment]
Resolved by https://github.com/johnnyreilly/jquery-validation-globalize/commit/6e22ba9cc27f14eadd9059715349ffc526c028b3

Just needs to be published to tested and then published to Bower. @sebrojas14 - if you'd like to have a play with it as it is then go for it.

**Comment by sebrojas14** [comment]
Good news :) I'm currently in a big project that is consuming all my time, so have no time to play with it :(. I hope you can release this soon so I can use it in the porject

**Comment by johnnyreilly** [comment]
Ha!  Surely that means you have all the time in the world to do testing? :smile:

Either way, I'm relatively confident that it's ready; it's available on Bower now as version 1.0.0 now.  I've done basic testing on it and the unit tests are all green.  Do let me know if there are any issues.

**Comment by sebrojas14** [comment]
Do you updated documentation and examples?
