### ISSUE TITLE
SCRIPT5009: "Globalize" is undefined

### ISSUE THREAD

**Issue by Otto404** [johnnyreilly/jquery-validation-globalize#9]
I'm using:
        bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                  "~/Scripts/jquery.validate*"
                         , "~/Scripts/jquery.globalize/globalize.js"
                       , "~/Scripts/jquery.globalize/cultures/globalize.culture.de-DE.js"
                      ));
and the error is: 
SCRIPT5009: "Globalize" is undefined
Datei: jquery.validate.globalize.js, Zeile: 6, Spalte: 2

**Comment by johnnyreilly** [comment]
Hi Otto,

Remember to serve up Globalize before any of the other scripts.
